import './globals.css';
import type {Metadata} from 'next';
import Footer from '@/components/footer/Footer';
import ThemeProvider from '@/components/contexts/ThemeContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='p-2'>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <main className='min-h-screen min-w-full'>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
